CREATE TABLE `TB_URL` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `URL` varchar(100) DEFAULT NULL,
  `REG_DT` datetime DEFAULT NULL,
  `LAST_CRAWL_START_DT` datetime NOT NULL,
  `LAST_CRAWL_END_DT` datetime DEFAULT NULL,
  `LAST_CRAWL_SUCCESS_DT` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `URL_UNIQUE` (`URL`)
);

CREATE TABLE `TB_COLOR` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `COLOR` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `COLOR_UNIQUE` (`COLOR`)
);

CREATE TABLE `TB_CASE` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `CASE` varchar(100) NOT NULL,
  `COLOR_ID` bigint NOT NULL,
  `REG_DT` datetime NOT NULL,
  `UPD_DT` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CASE_UNIQUE` (`CASE`),
  KEY `COLOR_ID` (`COLOR_ID`),
  CONSTRAINT `TB_CASE_FK_COLOR_ID` FOREIGN KEY (`COLOR_ID`) REFERENCES `TB_COLOR` (`ID`) ON UPDATE CASCADE
);

CREATE TABLE `REL_URL_CASE` (
  `ID` bigint NOT NULL,
  `URL_ID` bigint NOT NULL,
  `CASE_ID` bigint NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `URL_ID` (`URL_ID`),
  KEY `CASE_ID` (`CASE_ID`),
  CONSTRAINT `REL_URL_CASE_FK_URL_ID` FOREIGN KEY (`URL_ID`) REFERENCES `TB_URL` (`ID`) ON UPDATE CASCADE,
  CONSTRAINT `REL_URL_CASE_FK_CASE_ID` FOREIGN KEY (`CASE_ID`) REFERENCES `TB_CASE` (`ID`) ON UPDATE CASCADE
);